# i. Introduction to Python 1

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/gem-epidemics/colab/blob/master/iddinf/i_intro_to_python_1.ipynb)

In this session, we cover the Python syntax, commands, and patterns that will appear throughout the course. 

## LEARNING OUTCOMES
- Understand and work with key data structures
- User-defined functions
- Importing data and converting dataframes to array

## Using packages

Packages provide additional functionality and utility beyond the base Python build. To use a package, you must first install it so it becomes part of your "stack". This can be done in the terminal using the `pip install package_name` command or by using a Python environment manager such as `uv` (which we use for this course and highly recommend). Simply navigate to your project directory and use the command `uv add package_name` in your terminal. The environment created by `uv` can then be used to spin up a Jupyter kernel so that your notebook has access to all of the installed packages. 

The Jupyter notebooks used in this course are hosted on Google's Colab platform which already has an environment manager built in. You can access the terminal in a normal code cell by adding ! mark at the beginning of your terminal command. For e.g., you can install the `netCDF4` package (loads large datasets) by executing `!pip install netCDF4`.

In [89]:
# Uncomment the line below and run in Google Colab *only*
# !pip install netCDF4
# Use below otherwise
# %uv add netCDF4

Once a package is installed, you must `import` it into your script and notebook. Packages are loaded at the script/notebook level and as such, must be imported in every script that depends on them. Functions within a package are used with a `package_name.function_name` convention. You can give packages (abbreviated) aliases for convenience when importing them.

In [90]:
import numpy as np
import pandas as pd
import netCDF4
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns
import string

## Python syntax
The base Python build comes with an extensive suite of operators that lets you operate on variables in memory. The tables below group the operators according to the type operation the perform.

### Basics 

#### Arithmetic operators
These are used for basic arithmetic. 
| Operator | Name | Description | Example |
|----------|------|-------------|---------|
| `+` | Addition | Adds two numbers | `5 + 3` → `8` |
| `-` | Subtraction | Subtracts one number from another | `5 - 3` → `2` |
| `*` | Multiplication | Multiplies two numbers | `5 * 3` → `15` |
| `/` | Division | Divides one number by another (returns float) | `5 / 2` → `2.5` |
| `//` | Floor Division | Divides and rounds down to nearest integer | `5 // 2` → `2` |
| `%` | Modulus | Returns remainder after division | `5 % 2` → `1` |
| `**` | Exponentiation | Raises a number to a power | `5 ** 2` → `25` |

#### Comparison operators
These are used for performing boolean (true/false) evaluations. 
| Operator | Name | Description | Example |
|----------|------|-------------|---------|
| `==` | Equal to | Checks if two values are equal | `5 == 5` → `True` |
| `!=` | Not equal to | Checks if two values are different | `5 != 3` → `True` |
| `<` | Less than | Checks if left value is smaller | `3 < 5` → `True` |
| `>` | Greater than | Checks if left value is larger | `5 > 3` → `True` |
| `<=` | Less than or equal to | Checks if left value is smaller or equal | `5 <= 5` → `True` |
| `>=` | Greater than or equal to | Checks if left value is larger or equal | `5 >= 3` → `True` |

#### Logical operators
These are used for combining multiple conditons 
| Operator | Name | Description | Example |
|----------|------|-------------|---------|
| `and` | Logical AND | Both conditions must be True | `(5 > 3) and (3 < 10)` → `True` |
| `or` | Logical OR | At least one condition must be True | `(5 > 10) or (3 < 10)` → `True` |
| `not` | Logical NOT | Inverts the boolean value | `not (5 > 10)` → `True` |

#### Assignment operators 
These are used for assigning and modifying variables. 

| Operator | Name | Description | Example |
|----------|------|-------------|---------|
| `=` | Assignment | Assigns a value to a variable | `x = 5` |
| `+=` | Add and assign | Adds and assigns the result | `x = 5; x += 3` → `x = 8` |
| `-=` | Subtract and assign | Subtracts and assigns the result | `x = 5; x -= 2` → `x = 3` |
| `*=` | Multiply and assign | Multiplies and assigns the result | `x = 5; x *= 2` → `x = 10` |
| `/=` | Divide and assign | Divides and assigns the result | `x = 10; x /= 2` → `x = 5.0` |

### Data structures 

This section introduces the base data structures available to us in Python. The main structures we are interested in are 
- tuples 
- lists 
- dictionaries 
- namedtuples 

Naming rules:
1. names can include letters, numbers, and underscores
2. *cannot* start with a digit
3. Python *is* case senstive

#### Atoms

In [91]:
# scalar values stored in memory
X = 1  # a number
word = "one"  # a string

#### Tuples

Tuples are a collection of atoms that are immutable (i.e. the elements in the tuple cannot be added or removed once created). Atoms within a tuple can be accessed by using the index of the atom. A important thing to note is that **Python is a zero-indexed langauge** so the first entry is at index 0.

In [92]:
my_tup = (X, 2, X / 42, 87.1)

In [93]:
len(my_tup)

4

In [94]:
# my_tup[4] = "not allowed"

In [95]:
# access elements using integer values
print(f"First element: {my_tup[0]}")
print(f"Last element: {my_tup[3]}")
print(f"Last element (negative indexing): {my_tup[-1]:.4f}")
print(f"Multiple elements: {my_tup[1:3]}")

First element: 1
Last element: 87.1
Last element (negative indexing): 87.1000
Multiple elements: (2, 0.023809523809523808)

````{exercise-start}
:label: exi.2
````

Given the list below, do the following:

1. What is the 13th letter in the alphabet?
2. What are the 7th to 11th letters of the alphabet?
3. What is the middle letter of the alphabet?
4. Spell dog using elements of the list


**NOTE** Python is 0-indexed

In [96]:
# tuple of all lowercase letters in the English alphabet
alphabet = tuple(string.ascii_lowercase)  # tuple constructor

print(alphabet)

('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')

In [97]:
# 1. 13th letter

In [98]:
# 2. 7th to 11th

In [99]:
# 3. middle letter

In [100]:
# 4. dog

````{exercise-end}
````

````{solution-start} exi.2
:class: dropdown
````

In [101]:
# Solution
print(alphabet[12])

m

In [102]:
# Solution
print(alphabet[6 : 10 + 1])

('g', 'h', 'i', 'j', 'k')

In [103]:
# Solution
num_letters = len(alphabet)
print(num_letters)
print(alphabet[int(num_letters / 2) - 1])

26
m

In [104]:
# Solution
print(alphabet[3], alphabet[14], alphabet[6])

d o g

````{solution-end}
````

#### Lists
Lists are flexible structures since items can be of any type (eg. int, float, string, list, etc). Unlike tuples, lists *are* mutable so we can add or remove items from them.

In [105]:
my_list = [X, 2, X / 42, 87.1]  # a list - square brackets

In [106]:
len(my_list)

4

In [107]:
# indexing works the same way!
print(f"First element: {my_list[0]}")
print(f"Last element: {my_list[3]}")
print(f"Last element (negative indexing): {my_list[-1]:.4f}")
print(f"Multiple elements: {my_list[1:3]}")

First element: 1
Last element: 87.1
Last element (negative indexing): 87.1000
Multiple elements: [2, 0.023809523809523808]

In [108]:
# since they are mutable we can add values
my_list.append("allowed!")

In [109]:
my_list

[1, 2, 0.023809523809523808, 87.1, 'allowed!']

In [110]:
# can also remove entry
my_list.remove("allowed!")

In [111]:
my_list

[1, 2, 0.023809523809523808, 87.1]

In [112]:
# remove entry with specific index
my_list.pop(-1)

87.1

In [113]:
my_list

[1, 2, 0.023809523809523808]

````{exercise-start}
:label: exi.3
````

Someone made a typo when spelling 'dog'. Fix the following lists to the correct spelling.

In [114]:
dog_1 = ["d", "o", "h"]

In [115]:
# correct spelling

In [116]:
dog_2 = ["d", "g", "o"]

In [117]:
# correct spelling

````{exercise-end}
````

````{solution-start} exi.3
:class: dropdown
````

In [118]:
# correct spelling - Solution
dog_1[-1] = "g"
print(dog_1)

['d', 'o', 'g']

In [119]:
# correct spelling - Solution
dog_2 = [dog_2[0], dog_2[2], dog_2[1]]
print(dog_2)

['d', 'o', 'g']

````{solution-end}
````

````{tip} List or tuple?

The main difference between lists and tuples is **mutability**. Tuples are more efficient and less error prone, lists are more flexible and have more built-in methods. Often times it does not matter which you pick so think about how you want to interact with it downstream. 
````

#### Dictionaries
Dictionaries are a data structure that is used to hold key-value pairs. This is helpful as we can assign specific names to the keys that are descriptive of the value they are associated to. Dictionaries are defined within a pair \{ \} as shown below.

In [120]:
# define a dictionary
epi_case = {
    "name": "John Smith",
    "infected_date": "2024-01-01",
    "recovery_date": "2024-01-03",
    "age": 42,
}

print(epi_case)

{'name': 'John Smith', 'infected_date': '2024-01-01', 'recovery_date': '2024-01-03', 'age': 42}

In [121]:
# accessing elements of a dictionary

# option 1: using the key
epi_case["infected_date"]

'2024-01-01'

In Python, methods are function associated with an object that allow users to interact and/or modify the data within the object. Dictionaries have several methods available which can be found in the [python documentation](https://www.w3schools.com/python/python_dictionaries.asp).

In [122]:
# option 2: using the get method
epi_case.get("infected_date")

'2024-01-01'

In [123]:
epi_case.keys()

dict_keys(['name', 'infected_date', 'recovery_date', 'age'])

In [124]:
epi_case.values()

dict_values(['John Smith', '2024-01-01', '2024-01-03', 42])

Combining data with dict

In [125]:
# define 2 dictionary
epi_case1 = {
    "name": "John Smith",
    "infected_date": "2024-01-01",
    "recovery_date": "2024-01-03",
    "age": 42,
}

extra_data1 = {"hospitalize": True, "vacinated": False, "height": 175}

epi_case2 = {
    "name": "Jane Smith",
    "infected_date": "2024-01-02",
    "recovery_date": "2024-01-05",
    "age": 42,
}

In [126]:
# only works when there are NO overlapping keys
john_details = {**epi_case1, **extra_data1}
john_details

{'name': 'John Smith',
 'infected_date': '2024-01-01',
 'recovery_date': '2024-01-03',
 'age': 42,
 'hospitalize': True,
 'vacinated': False,
 'height': 175}

## Control flow 

### Loops
Like most other languages, Python comes with `for` and `while` loops. These are useful tools when you need to iterate over data structures.

In [127]:
for ii in range(5):
    print(f"Iteration #{ii}")

Iteration #0
Iteration #1
Iteration #2
Iteration #3
Iteration #4

In [128]:
ii = 0
num_steps = 5

while ii < num_steps:
    print(f"Iteration #{ii}")
    ii += 1

Iteration #0
Iteration #1
Iteration #2
Iteration #3
Iteration #4

Data structures like dictionaries which have key-value pairings can be iterated over by "unpacking" them. The `.item()` method of a dictionary returns two objects seperately. We can iterate over the pairings in a loop as such:

In [129]:
for key, values in epi_case.items():
    # pad with 15 characters left and right
    print(f"Key: {key:<15} | Value: {values:>15}")

Key: name            | Value:      John Smith
Key: infected_date   | Value:      2024-01-01
Key: recovery_date   | Value:      2024-01-03
Key: age             | Value:              42

### Conditional statements 

We can control the execution of a program based on specific conditions. The basic structure of a Python conditional statement is outlined in the code blocks below. It is worth noting that the indentation on code dictates the execution (languages like R use fences to encapsulate the scope of the condition).

In [130]:
# conditionl statement syntax

condition = True

if condition:
    print(f"My condition was {condition} so execute my program!")
elif not condition:
    print(f"My OTHER condition was {condition} so execute my program!")
else:
    print("Nothing interesting...")

My condition was True so execute my program!

Python also allows for in-line conditional statements. The behaviour is identical however they have a slightly different structure.

In [131]:
print("Main objective") if condition else print("Secondary task")

Main objective

````{exercise-start}
:label: exi.4
````

Using `epi_case` and the additional patient records below, practice writing `for` loops and in-line conditional statements.

**Setup:** run the cell below to create `case_list`, a list of patient dictionaries (including `epi_case`).

1. Loop through `case_list` and print each patient's name together with `"adult"` or `"minor"`, using an in-line conditional on `age >= 18`.
2. Loop through `epi_case.items()` and, using an in-line conditional, print only the keys that contain the word `"date"`.
3. Loop through `case_list` and count how many patients are minors (`age < 18`), updating a counter with an in-line conditional on each iteration.
4. Loop through `case_list`; for each patient, loop through its key-value pairs and print them, using an in-line conditional to append `" (sensitive)"` after the value when the key is `"age"`.

In [132]:
# additional patient records for the exercise
epi_case_b = {
    "name": "Alin Morariu",
    "infected_date": "2024-01-03",
    "recovery_date": "2024-01-10",
    "age": 17,
}
epi_case_c = {
    "name": "Jess Bridgen",
    "infected_date": "2024-01-04",
    "recovery_date": "2024-01-06",
    "age": 65,
}
epi_case_d = {
    "name": "Chris Jewell",
    "infected_date": "2024-01-05",
    "recovery_date": "2024-01-08",
    "age": 9,
}

case_list = (epi_case, epi_case_b, epi_case_c, epi_case_d)

In [133]:
# 1. adult or minor

In [134]:
# 2. keys containing "date"

In [135]:
# 3. count minors

In [136]:
# 4. flag sensitive age field

````{exercise-end}
````

````{solution-start} exi.4
:class: dropdown
````

In [137]:
# Solution
for case in case_list:
    label = "adult" if case["age"] >= 18 else "minor"
    print(f"{case['name']}: {label}")

John Smith: adult
Alin Morariu: minor
Jess Bridgen: adult
Chris Jewell: minor

In [138]:
# Solution
for key, value in epi_case.items():
    print(f"{key}: {value}") if "date" in key else None

infected_date: 2024-01-01
recovery_date: 2024-01-03

In [139]:
# Solution
minor_count = 0

for case in case_list:
    minor_count += 1 if case["age"] < 18 else 0

print(minor_count)

2

In [140]:
# Solution
for case in case_list:
    for key, value in case.items():
        value = f"{value} (sensitive)" if key == "age" else value
        print(f"{key}: {value}")
    print()

name: John Smith
infected_date: 2024-01-01
recovery_date: 2024-01-03
age: 42 (sensitive)

name: Alin Morariu
infected_date: 2024-01-03
recovery_date: 2024-01-10
age: 17 (sensitive)

name: Jess Bridgen
infected_date: 2024-01-04
recovery_date: 2024-01-06
age: 65 (sensitive)

name: Chris Jewell
infected_date: 2024-01-05
recovery_date: 2024-01-08
age: 9 (sensitive)

````{solution-end}

## Data types 

(bool, int, float32/float64, datetime) 

Its important to quickly discuss data types since they have strong implications when it comes to numerical computation. Python, like most other languages, ships with some basic data types (see table). 

| Category | Types |
|---|---|
| Text Type | `str` |
| Numeric Types | `int`, `float`, `complex` |
| Sequence Types | `list`, `tuple`, `range` |
| Mapping Type | `dict` |
| Boolean Type | `bool` |

You can check the type of any object by using the `type` function.

In [141]:
# e.g.
type(X)

int

In [142]:
type(epi_case)

dict

In [143]:
type(epi_case1["name"])

str

When doing numerical computation, we *must* be aware of the implications of our choice of data types. Python naturally tries to coerce types to allow for natural operations. For e.g.

In [144]:
# type int + type float = type float
X + 2.0

3.0

### Special data types 

On top of Python's base types, packages like `datetime` (standard library) and `numpy` provide additional types suited to specific tasks: `datetime` objects for doing arithmetic on calendar dates and times, and fixed-precision numeric types (`int32`/`int64`, `float32`/`float64`) for efficient numerical computation. These matter once you start doing serious numerical work, since the type you choose has downstream implications with respect to the accuracy and speed of your calculations.

#### `datetime`
Epidemiological data is almost always timestamped, so being able to do arithmetic on dates is essential (e.g. incubation periods, time-to-recovery). The `datetime` module lets us parse a date string into a `datetime` object using `datetime.strptime`, and once we have `datetime` objects, subtracting one from another gives us a `timedelta` representing the elapsed time between them. These are special types that provide convenience.

In [145]:
from datetime import datetime

infected = datetime.strptime(epi_case["infected_date"], "%Y-%m-%d")
recovered = datetime.strptime(epi_case["recovery_date"], "%Y-%m-%d")

recovery_time = recovered - infected
print(type(recovery_time))
print(f"{epi_case['name']} took {recovery_time.days} days to recover")

<class 'datetime.timedelta'>
John Smith took 2 days to recover

We can also add a `timedelta` back onto a `datetime` to project forward in time, e.g. scheduling a follow-up appointment 14 days after recovery:

In [146]:
from datetime import timedelta

follow_up = recovered + timedelta(days=14)
print(f"Follow-up appointment: {follow_up.strftime('%Y-%m-%d')}")

Follow-up appointment: 2024-01-17

````{exercise-start}
:label: exi.5
````

Using `case_list` (defined earlier), do the following:

1. Loop through `case_list`, parse each patient's `infected_date` and `recovery_date`, and print `"{name}: X days to recover"`.
2. Print the name of the patient with the *longest* recovery time.

In [147]:
# 1. days to recover

In [148]:
# 2. longest recovery

````{exercise-end}
````

````{solution-start} exi.5
:class: dropdown
````

In [149]:
# Solution
for case in case_list:
    infected = datetime.strptime(case["infected_date"], "%Y-%m-%d")
    recovered = datetime.strptime(case["recovery_date"], "%Y-%m-%d")
    days = (recovered - infected).days
    print(f"{case['name']}: {days} days to recover")

John Smith: 2 days to recover
Alin Morariu: 7 days to recover
Jess Bridgen: 2 days to recover
Chris Jewell: 3 days to recover

In [150]:
# Solution
longest_name = None
longest_days = -1

for case in case_list:
    infected = datetime.strptime(case["infected_date"], "%Y-%m-%d")
    recovered = datetime.strptime(case["recovery_date"], "%Y-%m-%d")
    days = (recovered - infected).days
    if days > longest_days:
        longest_days = days
        longest_name = case["name"]

print(f"{longest_name} had the longest recovery time ({longest_days} days)")

Alin Morariu had the longest recovery time (7 days)

````{solution-end}
````

#### `float32` vs `float64`
`numpy` gives us numeric types with a fixed number of bits, which controls both the *precision* of a value (how many significant digits it can represent) and its memory footprint. `float64` (double precision) uses 64 bits and is numpy's default; `float32` (single precision) uses half the memory, but stores fewer significant digits, which can introduce rounding error into a calculation.

In [151]:
# same calculation, different precision
a32 = np.float32(1) / np.float32(3)
a64 = np.float64(1) / np.float64(3)

print(f"float32: {a32:.20f}")
print(f"float64: {a64:.20f}")

float32: 0.33333334326744079590
float64: 0.33333333333333331483

That's the precision side of the trade-off. We can measure the speed side using the `timeit` module, which repeatedly runs a piece of code and reports how long it took.

In [152]:
import timeit

n = 10_000_000
x32 = np.ones(n, dtype=np.float32)
x64 = np.ones(n, dtype=np.float64)

time32 = timeit.timeit(lambda: x32 * x32, number=50)
time64 = timeit.timeit(lambda: x64 * x64, number=50)

print(f"float32: {time32:.4f}s")
print(f"float64: {time64:.4f}s")

float32: 0.2035s
float64: 0.2425s

Because `float64` carries twice as many bits through every operation, it is typically slower and uses more memory than `float32` for the same computation — that's the "cost" of its extra precision. As a rule of thumb: default to `float64` for numerical stability, and only drop to `float32` when memory or speed genuinely matter and you're confident the precision loss won't affect your results.

````{exercise-start}
:label: exi.6
````

Do the following:

1. Create two 1,000,000-element numpy arrays of ones: one `float32`, one `float64`. Using `timeit` (`number=1000`), time how long it takes to multiply each array by `0.1`, and print which dtype was faster.
2. Sum the two (multiplied) arrays from part 1 and print both sums. Are they exactly equal? Add a one-line comment explaining why or why not.

In [153]:
# 1. time float32 vs float64 multiplication

In [154]:
# 2. compare sums

````{exercise-end}
````

````{solution-start} exi.6
:class: dropdown
````

In [155]:
# Solution
m = 1_000_000
y32 = np.ones(m, dtype=np.float32)
y64 = np.ones(m, dtype=np.float64)

t32 = timeit.timeit(lambda: y32 * 0.1, number=1000)
t64 = timeit.timeit(lambda: y64 * 0.1, number=1000)

print(f"float32: {t32:.4f}s")
print(f"float64: {t64:.4f}s")
print("float32 was faster" if t32 < t64 else "float64 was faster")

float32: 0.1204s
float64: 0.3557s
float32 was faster

In [156]:
# Solution
sum32 = (y32 * 0.1).sum()
sum64 = (y64 * 0.1).sum()

print(f"float32 sum: {sum32:.10f}")
print(f"float64 sum: {sum64:.10f}")
# not exactly equal - float32 has fewer significant digits, so rounding error
# from each of the 1,000,000 multiplications accumulates differently
print(sum32 == sum64)

float32 sum: 100000.0078125000
float64 sum: 100000.0000000000
False

````{solution-end}
````

## Arrays 
Numpy is a popular Python package that is focused on numerical computation. It is used for creating numerical arrays and provides performant implementations of many mathematical operations (e.g. mathematical functions, random number generation, linear algebra, etc.). 

By convention, the `numpy` package is imported and aliased with `np` (see above). Arrays carry less auxiliary information than data frames (more of these shortly) and so, they are faster for numerical computation. 


Accessing values, broadcasting, dimensions/rank

In [157]:
# We can define an array using a list:
infection_times = np.array([1.5, 3.2, 9.0, 4.0, 4.3])

# We can then access an element of the array
# NB: remember in Python structures are zero indexed
print(infection_times[0])

1.5

In [158]:
# Defining a 2-D array
connectivity_matrix = np.array([[0, 1.5, 0.25], [1.5, 0, 0.5], [0.25, 0.5, 0]])

# We can access elements and rows/columns in the same way
print(connectivity_matrix[0, 2])

0.25

Arrays can be multi-dimensional and mathematical operations can be broadcasted across the axes. The way the arrays are broadcasted comes down to the shapes. In the example below, we take a connectivity matrix that changes over time along with an array of vectors of the population at the respective time stamps.

In [159]:
connectivity_matrix_over_time = np.array(
    [
        [[0, 1.5, 0.25], [1.5, 0, 0.5], [0.25, 0.5, 0]],  # time 1
        [[0, 1.7, 0.5], [1.7, 0, 0.5], [0.5, 0.5, 0]],  # time 2
        [[0, 2.0, 0.1], [2.0, 0, 0.25], [0.1, 0.25, 0]],  # time 3
    ]
)

population_count_v1 = np.array(
    [
        [100, 50, 25],  # time 1
        [125, 75, 5],  # time 2
        [250, 50, 10],  # time 3
    ],
)

# notice the difference in number of squre brackets
population_count_v2 = np.array(
    [
        [[100], [50], [25]],  # time 1
        [[125], [75], [5]],  # time 2
        [[250], [50], [10]],  # time 3
    ]
)

In [160]:
population_count_v1.transpose()

array([[100, 125, 250],
       [ 50,  75,  50],
       [ 25,   5,  10]])

Let's look at the shapes of the structures we just created and then do some matrix-vector multiplication to see the different behaviours.

In [161]:
print(f"Connectivity matrix shape: {connectivity_matrix.shape}")
print(f"Connectivity matricies over time shape: {connectivity_matrix_over_time.shape}")

print(f"Population vectors V1 shape: {population_count_v1.shape}")
print(f"Population vectors V2 shape: {population_count_v2.shape}")

Connectivity matrix shape: (3, 3)
Connectivity matricies over time shape: (3, 3, 3)
Population vectors V1 shape: (3, 3)
Population vectors V2 shape: (3, 3, 1)

In [162]:
# connectivity matrix x population counts over time
np.matmul(connectivity_matrix, population_count_v1)

array([[250.  , 125.  ,  10.  ],
       [275.  , 100.  ,  42.5 ],
       [ 87.5 ,  50.  ,   8.75]])

In [163]:
# connectivity matrix x population counts over time
np.matmul(connectivity_matrix, population_count_v2)

array([[[ 81.25],
        [162.5 ],
        [ 50.  ]],

       [[113.75],
        [190.  ],
        [ 68.75]],

       [[ 77.5 ],
        [380.  ],
        [ 87.5 ]]])

In [164]:
# connectivity matrix x population counts over time
np.matmul(connectivity_matrix_over_time, population_count_v1)

array([[[250.  , 125.  ,  10.  ],
        [275.  , 100.  ,  42.5 ],
        [ 87.5 ,  50.  ,   8.75]],

       [[337.5 , 152.5 ,  13.5 ],
        [295.  , 110.  ,  47.5 ],
        [112.5 ,  62.5 ,  15.  ]],

       [[275.  , 155.  ,  11.  ],
        [262.5 , 112.5 ,  52.5 ],
        [ 41.25,  23.75,   3.75]]])

In [165]:
# connectivity matrix x population counts over time - notice this now produces 3 vectors each of dimension 3
np.matmul(connectivity_matrix_over_time, population_count_v2)

array([[[ 81.25],
        [162.5 ],
        [ 50.  ]],

       [[130.  ],
        [215.  ],
        [100.  ]],

       [[101.  ],
        [502.5 ],
        [ 37.5 ]]])

The four `matmul` calls above all illustrate the same point: broadcasting is driven by the *trailing* (last two) axes of the arrays. `np.matmul` treats an array's final two dimensions as the matrix to multiply and treats any leading dimensions as a "batch" that gets broadcast over. `connectivity_matrix` has shape `(3, 3)` — a single matrix — while `connectivity_matrix_over_time` has shape `(3, 3, 3)`, i.e. a batch of three `(3, 3)` matrices (one per time step). Multiplying the single matrix against `population_count_v1` (shape `(3, 3)`) or `population_count_v2` (shape `(3, 3, 1)`) just performs one matrix-matrix or matrix-vector product, and the trailing dimensions (`3, 3`) x (`3, 3`) or (`3, 3`) x (`3, 1`) must be compatible for the multiplication to be defined. Multiplying the *time-varying* connectivity matrices against `population_count_v1` or `population_count_v2` broadcasts the single population array across the leading (time) axis of `connectivity_matrix_over_time`, applying the appropriate connectivity matrix to the population at each time step and returning a stack of three results. In every case, it is the shape of the trailing two axes — not the overall number of dimensions — that dictates whether the operation is valid and what shape the result takes.

````{exercise-start}
:label: exi.7
````

Using the setup below, do the following:

1. Create a 2-D numpy array `case_counts` with shape `(3, 4)` holding daily case counts for 3 regions over 4 days: Region A: `[5, 8, 12, 7]`, Region B: `[2, 3, 5, 4]`, Region C: `[10, 15, 9, 6]`.
2. Print Region B's case count on day 3 using indexing.
3. Investigators believe true case counts are `1.2` times higher due to under-reporting. Multiply `case_counts` by `1.2` (broadcasting) and print the result.

In [166]:
# 1. create case_counts

In [167]:
# 2. Region B, day 3

In [168]:
# 3. adjust for under-reporting

````{exercise-end}
````

````{solution-start} exi.7
:class: dropdown
````

In [169]:
# Solution
case_counts = np.array(
    [
        [5, 8, 12, 7],  # Region A
        [2, 3, 5, 4],  # Region B
        [10, 15, 9, 6],  # Region C
    ]
)

print(case_counts)

[[ 5  8 12  7]
 [ 2  3  5  4]
 [10 15  9  6]]

In [170]:
# Solution
print(case_counts[1, 2])

5

In [171]:
# Solution
adjusted_counts = case_counts * 1.2
print(adjusted_counts)

[[ 6.   9.6 14.4  8.4]
 [ 2.4  3.6  6.   4.8]
 [12.  18.  10.8  7.2]]

````{solution-end}
````

## Importing and viewing data

`pandas` is the Python package that is used for creating and working with DataFrames. In this section, we look at importing data from different locations and from different types. After that, we convert them to pandas DataFrames and examine them.

### What is a DataFrame?

A **DataFrame** is `pandas`' core data structure. It is a 2-dimensional, labelled table that looks a lot like a spreadsheet. Unlike a `numpy` array, where the elements must all have the same dtype, each *column* of a DataFrame can hold a different type (e.g. names as `str`, ages as `float`, dates as `datetime`). Each value within a single column shares the same type. Each column has a name and each row has an index which is helpful for accessing values.

### What is an xarray?

An **xarray** is `xarray`' core data structure that generalized 2D `pandas` DataFrames into multi-dimensional labelled arrays. At its core, it behaves like `numpy` but adds extra functionality by being able to access (and operate) via the labels. For now, we will only show how to import a dataset with `xarray` but further examples can be found in the online [tutorials](https://docs.xarray.dev/en/stable/getting-started-guide/tutorials-and-videos.html).

### Bringing in data from different sources

Both pakcages can read data from a **local paths** or from a **URL**. The reader function you call (`pd.read_csv`, `xr.open_dataset`, etc.) doesn't care which kind of source you give it, as long as the string you pass resolves to a valid file. Below, we load the same Hagelloch measles outbreak dataset twice: once from a file on disc, and once from a link.

In [172]:
# import data from disc
HAGELLOCH_DATA = xr.open_dataset("data/hagelloch.nc")

HAGELLOCH_DATA

<xarray.Dataset> Size: 1MB
Dimensions:        (node_id: 187, parent_id: 187)
Coordinates:
  * node_id        (node_id) int32 748B 1 2 3 4 5 6 ... 182 183 184 185 186 187
    parent_id      (node_id) int32 748B ...
Data variables:
    household_mat  (node_id, parent_id) float64 280kB ...
    class1_mat     (node_id, parent_id) float64 280kB ...
    class2_mat     (node_id, parent_id) float64 280kB ...
    distance_mat   (node_id, parent_id) float64 280kB ...
    si_time        (node_id) int32 748B ...
    ir_time        (node_id) int32 748B ...
Attributes:
    description:  Data on the 1861 measles outbreak in Hagelloch, taken from ...

In [185]:
# import data from web
HAGELLOCH_DATA = (
    "https://drive.google.com/uc?export=download&id=1T-O_51EsNy2FmqnHkR_7pHZnDGC28IeC"
)

data = pd.read_csv(HAGELLOCH_DATA)

data

,PN,NAME,FN,HN,AGE,SEX,PRO,ERU,CL,DEAD,...,GE,TD,TM,x.loc,y.loc,tPRO,tERU,tDEAD,tR,tI
0,1,Mueller,41,61,7.0,female,1861-11-21,1861-11-25,1st class,NaN,...,1,NaN,NaN,142.5,100.0,22.712422,26.225408,NaN,29.225408,21.712422
1,2,Mueller,41,61,6.0,female,1861-11-23,1861-11-27,1st class,NaN,...,1,3.0,40.3,142.5,100.0,24.211695,28.791124,NaN,31.791124,23.211695
2,3,Mueller,41,61,4.0,female,1861-11-28,1861-12-02,preschool,NaN,...,2,1.0,40.5,142.5,100.0,29.591023,33.691213,NaN,36.691213,28.591023
3,4,Seibold,61,62,13.0,male,1861-11-27,1861-11-28,2nd class,NaN,...,1,3.0,40.7,165.0,102.5,28.116983,29.028658,NaN,32.028658,27.116983
4,5,Motzer,42,63,8.0,female,1861-11-22,1861-11-27,1st class,NaN,...,1,NaN,NaN,145.0,120.0,23.059533,28.415100,NaN,31.415100,22.059533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,184,NN,51,6,13.0,NaN,1861-10-30,1861-11-06,2nd class,NaN,...,1,NaN,NaN,182.5,200.0,0.734982,7.983840,NaN,10.983840,-0.265018
184,185,Schneck,21,15,3.0,male,1861-12-03,1861-12-07,preschool,NaN,...,2,NaN,NaN,205.0,182.5,34.405657,38.952290,NaN,41.952290,33.405657
185,186,Motzer,57,33,6.0,NaN,1861-11-22,1861-11-26,preschool,NaN,...,1,NaN,NaN,212.5,90.0,23.518710,27.070649,NaN,30.070649,22.518710
186,187,Schneck,21,15,0.5,male,1861-12-07,1861-12-11,preschool,NaN,...,2,NaN,NaN,205.0,182.5,38.734967,42.230714,NaN,45.230714,37.734967
187,188,Motzer,57,33,1.0,NaN,1861-11-23,1861-11-27,preschool,NaN,...,1,NaN,NaN,212.5,90.0,24.435410,28.798919,NaN,31.798919,23.435410

````{tip} Does the file format matter?

`.csv` files are plain text which makes them a great default for flat, rectangular data like a line list. `.nc` (NetCDF) files are binary and self-describing and tend to read/write faster for large datasets (better management of multiple dimensions/labels).

In practice: if your data is a single flat table, `.csv` is usually the right (and most portable) choice. Consider a format like `.nc` only once your data has real multi-dimensional structure (e.g. a matrix that varies over time), or you're working at a scale where file size and read speed becomes a bottleneck.
````

### Exploring a DataFrame with pandas

Once loaded, `data` gives us the Hagelloch measles line list as a table of 188 cases (rows) and 26 recorded fields (columns). Typing the name (or letting it be the last line of a cell) displays the whole table, while DataFrame methods like `.shape` and `.columns` tells us how many rows and columns we have, and  the column names respectively:

In [175]:
print(data.shape)
print(data.columns)

(188, 26)
Index(['PN', 'NAME', 'FN', 'HN', 'AGE', 'SEX', 'PRO', 'ERU', 'CL', 'DEAD',
       'IFTO', 'SI', 'C', 'PR', 'CA', 'NI', 'GE', 'TD', 'TM', 'x.loc', 'y.loc',
       'tPRO', 'tERU', 'tDEAD', 'tR', 'tI'],
      dtype='object')

`.dtypes` shows the data type pandas inferred for each column:

In [176]:
data.dtypes

PN         int64
NAME      object
FN         int64
HN         int64
AGE      float64
SEX       object
PRO       object
ERU       object
CL        object
DEAD      object
IFTO     float64
SI         int64
C         object
PR         int64
CA         int64
NI         int64
GE         int64
TD       float64
TM       float64
x.loc    float64
y.loc    float64
tPRO     float64
tERU     float64
tDEAD    float64
tR       float64
tI       float64
dtype: object

`.head()` and `.tail()` preview just the first or last few rows — much more manageable than printing the whole table:

In [177]:
data.head()

,PN,NAME,FN,HN,AGE,SEX,PRO,ERU,CL,DEAD,...,GE,TD,TM,x.loc,y.loc,tPRO,tERU,tDEAD,tR,tI
0,1,Mueller,41,61,7.0,female,1861-11-21,1861-11-25,1st class,NaN,...,1,NaN,NaN,142.5,100.0,22.712422,26.225408,NaN,29.225408,21.712422
1,2,Mueller,41,61,6.0,female,1861-11-23,1861-11-27,1st class,NaN,...,1,3.0,40.3,142.5,100.0,24.211695,28.791124,NaN,31.791124,23.211695
2,3,Mueller,41,61,4.0,female,1861-11-28,1861-12-02,preschool,NaN,...,2,1.0,40.5,142.5,100.0,29.591023,33.691213,NaN,36.691213,28.591023
3,4,Seibold,61,62,13.0,male,1861-11-27,1861-11-28,2nd class,NaN,...,1,3.0,40.7,165.0,102.5,28.116983,29.028658,NaN,32.028658,27.116983
4,5,Motzer,42,63,8.0,female,1861-11-22,1861-11-27,1st class,NaN,...,1,NaN,NaN,145.0,120.0,23.059533,28.415100,NaN,31.415100,22.059533

`.info()` gives a compact summary — column names, non-null counts, and dtypes all at once — useful for spotting missing data:

In [178]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PN      188 non-null    int64
 1   NAME    188 non-null    object
 2   FN      188 non-null    int64
 3   HN      188 non-null    int64
 4   AGE     188 non-null    float64
 5   SEX     177 non-null    object
 6   PRO     188 non-null    object
 7   ERU     188 non-null    object
 8   CL      188 non-null    object
 9   DEAD    12 non-null     object
 10  IFTO    184 non-null    float64
 11  SI      188 non-null    int64
 12  C       188 non-null    object
 13  PR      188 non-null    int64
 14  CA      188 non-null    int64
 15  NI      188 non-null    int64
 16  GE      188 non-null    int64
 17  TD      79 non-null     float64
 18  TM      79 non-null     float64
 19  x.loc   188 non-null    float64
 20  y.loc   188 non-null    float64
 21  tPRO    188 non-null    float64
 22  tERU    188 non-null    float64
 23  tDEAD   12 non-null     float64
 24  tR      188 non-null    float64
 25  tI      188 non-null    float64
dtypes: float64(11), int64(8), object(7)
memory usage: 38.3+ KB

`.describe()` computes summary statistics (count, mean, std, min/max, quartiles) for every numeric column:

In [179]:
data.describe()

,PN,FN,HN,AGE,IFTO,SI,PR,CA,NI,GE,TD,TM,x.loc,y.loc,tPRO,tERU,tDEAD,tR,tI
count,188.000000,188.000000,188.000000,188.000000,184.000000,188.000000,188.000000,188.000000,188.000000,188.000000,79.000000,79.000000,188.000000,188.000000,188.000000,188.000000,12.000000,188.000000,188.000000
mean,94.500000,30.952128,35.329787,7.023936,82.152174,10.170213,3.946809,3.478723,1.728723,1.414894,2.607595,39.946835,188.218085,133.776596,30.563474,34.523380,43.983126,37.496263,29.563474
std,54.415071,16.587891,22.332149,4.252173,64.197600,2.240313,1.738935,1.545936,0.749919,0.494019,1.807518,0.729214,59.089145,67.042413,8.908252,8.783511,9.101703,8.808410,8.908252
min,1.000000,1.000000,2.000000,0.500000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,38.300000,7.500000,5.000000,0.734982,4.197762,19.516832,7.197762,-0.265018
25%,47.750000,18.000000,15.750000,3.000000,31.000000,9.000000,3.000000,2.000000,1.000000,1.000000,1.000000,39.550000,145.000000,80.000000,24.198089,28.783444,43.155097,31.783444,23.198089
50%,94.500000,31.000000,32.500000,7.000000,50.500000,10.000000,4.000000,3.000000,2.000000,1.000000,2.000000,40.100000,182.500000,147.500000,32.199539,36.608067,45.281375,39.608067,31.199539
75%,141.250000,43.000000,50.250000,11.000000,153.000000,11.000000,5.000000,4.000000,2.000000,2.000000,3.000000,40.500000,240.000000,187.500000,35.393452,38.789062,46.414566,41.714866,34.393452
max,188.000000,69.000000,80.000000,15.000000,188.000000,16.000000,13.000000,7.000000,3.000000,2.000000,11.000000,41.500000,280.000000,240.000000,86.688298,89.545238,59.863460,92.545238,85.688298

Select a single column with square-bracket indexing — this returns a pandas `Series`:

In [180]:
data["AGE"]

0       7.0
1       6.0
2       4.0
3      13.0
4       8.0
       ...
183    13.0
184     3.0
185     6.0
186     0.5
187     1.0
Name: AGE, Length: 188, dtype: float64

Select rows and columns together with `.loc` (label-based) or `.iloc` (position-based). For example, the age and sex of the first 5 cases:

In [ ]:
# label-based accessing
data.loc[0:4, ["AGE", "SEX"]]

    AGE     SEX
0   7.0  female
1   6.0  female
2   4.0  female
3  13.0    male
4   8.0  female

In [ ]:
# position-based indexing
data.iloc[0:4, [4, 5]]

    AGE     SEX
0   7.0  female
1   6.0  female
2   4.0  female
3  13.0    male

Finally, `.value_counts()` tallies how many times each value appears in a column — handy for a quick breakdown of a categorical field, like school class:

In [182]:
data["CL"].value_counts()

CL
preschool    90
2nd class    68
1st class    30
Name: count, dtype: int64